apiVersion: v2
version: 0.1.1

name: knowledge-admin
type: application
description: A Helm chart for deploying the LANTERN Knowledge Admin Interface.
home: https://github.com/lantern-compliance/charts

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.x.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 21.x.x
  - name: reactor
    repository: https://charts.kube-reactor.com
    version: 0.2.x

maintainers:
  - email: adrian@cellebris.com
    name: adrianwebb
    url: https://github.com/adrianwebb
