origin-cert:
  data:
    "server.key": "${APP_KEY}"
    "server.crt": "${APP_CERT}"

db:
  data:
    postgres-password: "${POSTGRESQL_PASSWORD}"
    replication-password: "${POSTGRESQL_PASSWORD}"
    password: "${POSTGRESQL_PASSWORD}"

global:
  data:
    PUBLIC_COMPANY_NAME: "${COMPANY_NAME}"

    BETTER_AUTH_SECRET: "${AUDIT_CHAT_AUTH_SECRET}"

    MAILGUN_URL: "${MAILGUN_API_URL}"
    MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
    MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"

    SEND_FROM_EMAIL: "noreply@${MAILGUN_DOMAIN}"

    POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"

    ZIMAGI_USER: "${ZIMAGI_ADMIN_USER}"
    ZIMAGI_TOKEN: "${ZIMAGI_DEFAULT_ADMIN_TOKEN}"
